name: Deploy JackpotOracle Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET (using .NET 9)
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0

      # Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Build the Blazor app for production
      - name: Build JackpotOracle Blazor App
        run: dotnet publish -c Release -o ./wwwroot

      - name: Move index.html to root (for GitHub Pages)
        run: |
          mv ./publish/wwwroot/index.html ./wwwroot/index.html
          
      # Deploy to GitHub Pages using a GitHub Action
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./wwwroot   # Directory to publish (your Blazor WebAssembly build)
          github_token: ${{ secrets.JACKPOTORACLE_APP_TOKEN }}
