name: build and test and deploy
env:
  PUBLISH_DIR: bin/Release/net9.0/publish/wwwroot
  
# Controls when the action will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish -c Release -o:public -p:GHPages=true
        
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
            html_path: ${{ env.PUBLISH_DIR }}/index.html
            base_href: /JackpotOracle/
        
      - name: Disable Jekyll
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
        
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
            target_branch: gh-pages
            build_dir: ${{ env.PUBLISH_DIR }}
        env:
            GITHUB_TOKEN: ${{ secrets.JACKPOTORACLE_APP_TOKEN }}